<template>
  <Button text="ایموجی" @click="dialog = true">
    <v-icon icon="mdi-emoticon-outline" />
  </Button>

  <v-dialog v-model="dialog" max-width="600px">
    <v-card>
      <v-card-title class="card-title">شکلک ها</v-card-title>
      <v-card-text class="inner-container">
        <v-container fluid>
          <v-row>
            <v-col cols="3">
              <v-list>
                <v-list-item
                  v-for="category in categories"
                  :key="category.value"
                  :class="{
                    'bg-grey-lighten-4': selectedCategory === category.value,
                  }"
                  @click="selectCategory(category.value)"
                >
                  <v-list-item-title>{{ category.label }}</v-list-item-title>
                </v-list-item>
              </v-list>
            </v-col>
            <v-col cols="9">
              <div>
                <v-text-field v-model="search" dense label="جستجو" />
              </div>
              <div class="chars-container">
                <div v-for="char in filteredCharacters" :key="char.value">
                  <button class="char-btn" @click="insertCharacter(char.value)">
                    <span v-html="char.value" />
                  </button>
                </div>
              </div>
            </v-col>
          </v-row>
        </v-container>
      </v-card-text>
      <v-card-actions>
        <v-spacer></v-spacer>
        <Button class="button" @click="dialog = false">بستن</Button>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<script lang="ts" setup>
import { ref, computed } from "vue";
import Button from "../components/Button.vue";
import type { Editor } from "@tiptap/core";
import { useNotifier } from "../notifier/useNotifier";

type Emoji = { label: string; value: string };
type EmojisCategories =
  | "smileys_people"
  | "animals_nature"
  | "food_drink"
  | "travel_places"
  | "activities"
  | "objects"
  | "symbols"
  | "flags";

const dialog = ref<boolean>(false);
const search = ref<string>("");
const selectedCategory = ref<EmojisCategories>("smileys_people");
const props = defineProps<{ editor: Editor }>();
const { notify } = useNotifier();

const categories: { label: string; value: EmojisCategories }[] = [
  { label: "لبخندها", value: "smileys_people" },
  { label: "حیوانات", value: "animals_nature" },
  { label: "خوراکی‌ها", value: "food_drink" },
  { label: "مکان‌ها", value: "travel_places" },
  { label: "فعالیت‌ها", value: "activities" },
  { label: "اشیا", value: "objects" },
  { label: "نمادها", value: "symbols" },
  // { label: "پرچم‌ها", value: "flags" },
];

const characters: Record<EmojisCategories, Emoji[]> = {
  smileys_people: [
    { label: "grinning", value: "😀" },
    { label: "grimacing", value: "😬" },
    { label: "grin", value: "😁" },
    { label: "joy", value: "😂" },
    { label: "rofl", value: "🤣" },
    { label: "partying", value: "🥳" },
    { label: "smiley", value: "😃" },
    { label: "smile", value: "😄" },
    { label: "sweat smile", value: "😅" },
    { label: "laughing", value: "😆" },
    { label: "innocent", value: "😇" },
    { label: "wink", value: "😉" },
    { label: "blush", value: "😊" },
    { label: "slightly smiling face", value: "🙂" },
    { label: "upside down face", value: "🙃" },
    { label: "relaxed", value: "☺️" },
    { label: "yum", value: "😋" },
    { label: "relieved", value: "😌" },
    { label: "heart eyes", value: "😍" },
    { label: "smiling face with three hearts", value: "🥰" },
    { label: "kissing heart", value: "😘" },
    { label: "kissing", value: "😗" },
    { label: "kissing smiling eyes", value: "😙" },
    { label: "kissing closed eyes", value: "😚" },
    { label: "stuck out tongue winking eye", value: "😜" },
    { label: "zany", value: "🤪" },
    { label: "raised eyebrow", value: "🤨" },
    { label: "monocle", value: "🧐" },
    { label: "stuck out tongue closed eyes", value: "😝" },
    { label: "stuck out tongue", value: "😛" },
    { label: "money mouth face", value: "🤑" },
    { label: "nerd face", value: "🤓" },
    { label: "sunglasses", value: "😎" },
    { label: "star struck", value: "🤩" },
    { label: "clown face", value: "🤡" },
    { label: "cowboy hat face", value: "🤠" },
    { label: "hugs", value: "🤗" },
    { label: "smirk", value: "😏" },
    { label: "no mouth", value: "😶" },
    { label: "neutral face", value: "😐" },
    { label: "expressionless", value: "😑" },
    { label: "unamused", value: "😒" },
    { label: "roll eyes", value: "🙄" },
    { label: "thinking", value: "🤔" },
    { label: "lying face", value: "🤥" },
    { label: "hand over mouth", value: "🤭" },
    { label: "shushing", value: "🤫" },
    { label: "symbols over mouth", value: "🤬" },
    { label: "exploding head", value: "🤯" },
    { label: "flushed", value: "😳" },
    { label: "disappointed", value: "😞" },
    { label: "worried", value: "😟" },
    { label: "angry", value: "😠" },
    { label: "rage", value: "😡" },
    { label: "pensive", value: "😔" },
    { label: "confused", value: "😕" },
    { label: "slightly frowning face", value: "🙁" },
    { label: "frowning face", value: "☹️" },
    { label: "persevere", value: "😣" },
    { label: "confounded", value: "😖" },
    { label: "tired face", value: "😫" },
    { label: "weary", value: "😩" },
    { label: "pleading", value: "🥺" },
    { label: "triumph", value: "😤" },
    { label: "open mouth", value: "😮" },
    { label: "scream", value: "😱" },
    { label: "fearful", value: "😨" },
    { label: "cold sweat", value: "😰" },
    { label: "hushed", value: "😯" },
    { label: "frowning", value: "😦" },
    { label: "anguished", value: "😧" },
    { label: "cry", value: "😢" },
    { label: "disappointed relieved", value: "😥" },
    { label: "drooling face", value: "🤤" },
    { label: "sleepy", value: "😪" },
    { label: "sweat", value: "😓" },
    { label: "hot", value: "🥵" },
    { label: "cold", value: "🥶" },
    { label: "sob", value: "😭" },
    { label: "dizzy face", value: "😵" },
    { label: "astonished", value: "😲" },
    { label: "zipper mouth face", value: "🤐" },
    { label: "nauseated face", value: "🤢" },
    { label: "sneezing face", value: "🤧" },
    { label: "vomiting", value: "🤮" },
    { label: "mask", value: "😷" },
    { label: "face with thermometer", value: "🤒" },
    { label: "face with head bandage", value: "🤕" },
    { label: "woozy", value: "🥴" },
    { label: "sleeping", value: "😴" },
    { label: "zzz", value: "💤" },
    { label: "poop", value: "💩" },
    { label: "smiling imp", value: "😈" },
    { label: "imp", value: "👿" },
    { label: "japanese ogre", value: "👹" },
    { label: "japanese goblin", value: "👺" },
    { label: "skull", value: "💀" },
    { label: "ghost", value: "👻" },
    { label: "alien", value: "👽" },
    { label: "robot", value: "🤖" },
    { label: "smiley cat", value: "😺" },
    { label: "smile cat", value: "😸" },
    { label: "joy cat", value: "😹" },
    { label: "heart eyes cat", value: "😻" },
    { label: "smirk cat", value: "😼" },
    { label: "kissing cat", value: "😽" },
    { label: "scream cat", value: "🙀" },
    { label: "crying cat face", value: "😿" },
    { label: "pouting cat", value: "😾" },
  ],
  symbols: [
    { value: "💯", label: "100" },
    { value: "🔢", label: "1234" },
    { value: "❤️", label: "heart" },
    { value: "🧡", label: "orange heart" },
    { value: "💛", label: "yellow heart" },
    { value: "💚", label: "green heart" },
    { value: "💙", label: "blue heart" },
    { value: "💜", label: "purple heart" },
    { value: "🖤", label: "black heart" },
    { value: "💔", label: "broken heart" },
    { value: "❣", label: "heavy heart exclamation" },
    { value: "💕", label: "two hearts" },
    { value: "💞", label: "revolving hearts" },
    { value: "💓", label: "heartbeat" },
    { value: "💗", label: "heartpulse" },
    { value: "💖", label: "sparkling heart" },
    { value: "💘", label: "cupid" },
    { value: "💝", label: "gift heart" },
    { value: "💟", label: "heart decoration" },
    { value: "☮", label: "peace symbol" },
    { value: "✝", label: "latin cross" },
    { value: "☪", label: "star and crescent" },
    { value: "🕉", label: "om" },
    { value: "☸", label: "wheel of dharma" },
    { value: "✡", label: "star of david" },
    { value: "🔯", label: "six pointed star" },
    { value: "🕎", label: "menorah" },
    { value: "☯", label: "yin yang" },
    { value: "☦", label: "orthodox cross" },
    { value: "🛐", label: "place of worship" },
    { value: "⛎", label: "ophiuchus" },
    { value: "♈", label: "aries" },
    { value: "♉", label: "taurus" },
    { value: "♊", label: "gemini" },
    { value: "♋", label: "cancer" },
    { value: "♌", label: "leo" },
    { value: "♍", label: "virgo" },
    { value: "♎", label: "libra" },
    { value: "♏", label: "scorpius" },
    { value: "♐", label: "sagittarius" },
    { value: "♑", label: "capricorn" },
    { value: "♒", label: "aquarius" },
    { value: "♓", label: "pisces" },
    { value: "🆔", label: "id" },
    { label: "atom symbol", value: "⚛" },
    { label: "u7a7a", value: "🈳" },
    { label: "u5272", value: "🈹" },
    { label: "radioactive", value: "☢" },
    { label: "biohazard", value: "☣" },
    { label: "mobile phone off", value: "📴" },
    { label: "vibration mode", value: "📳" },
    { label: "u6709", value: "🈶" },
    { label: "u7121", value: "🈚" },
    { label: "u7533", value: "🈸" },
    { label: "u55b6", value: "🈺" },
    { label: "u6708", value: "🈷️" },
    { label: "eight pointed black star", value: "✴️" },
    { label: "vs", value: "🆚" },
    { label: "accept", value: "🉑" },
    { label: "white flower", value: "💮" },
    { label: "ideograph advantage", value: "🉐" },
    { label: "secret", value: "㊙️" },
    { label: "congratulations", value: "㊗️" },
    { label: "u5408", value: "🈴" },
    { label: "u6e80", value: "🈵" },
    { label: "u7981", value: "🈲" },
    { label: "a", value: "🅰️" },
    { label: "b", value: "🅱️" },
    { label: "ab", value: "🆎" },
    { label: "cl", value: "🆑" },
    { label: "o2", value: "🅾️" },
    { label: "sos", value: "🆘" },
    { label: "no entry", value: "⛔" },
    { label: "name badge", value: "📛" },
    { label: "no entry sign", value: "🚫" },
    { label: "x", value: "❌" },
    { label: "o", value: "⭕" },
    { label: "stop sign", value: "🛑" },
    { label: "anger", value: "💢" },
    { label: "hotsprings", value: "♨️" },
    { label: "no pedestrians", value: "🚷" },
    { label: "do not litter", value: "🚯" },
    { label: "no bicycles", value: "🚳" },
    { label: "non potable water", value: "🚱" },
    { label: "underage", value: "🔞" },
    { label: "no mobile phones", value: "📵" },
    { label: "exclamation", value: "❗" },
    { label: "grey exclamation", value: "❕" },
    { label: "question", value: "❓" },
    { label: "grey question", value: "❔" },
    { label: "bangbang", value: "‼️" },
    { label: "interrobang", value: "⁉️" },
    { label: "low brightness", value: "🔅" },
    { label: "high brightness", value: "🔆" },
    { label: "trident", value: "🔱" },
    { label: "fleur de lis", value: "⚜" },
    { label: "part alternation mark", value: "〽️" },
    { label: "warning", value: "⚠️" },
    { label: "children crossing", value: "🚸" },
    { value: "🔰", label: "beginner" },
    { value: "♻️", label: "recycle" },
    { value: "🈯", label: "u6307" },
    { value: "💹", label: "chart" },
    { value: "❇️", label: "sparkle" },
    { value: "✳️", label: "eight spoked asterisk" },
    { value: "❎", label: "negative squared cross mark" },
    { value: "✅", label: "white check mark" },
    { value: "💠", label: "diamond shape with a dot inside" },
    { value: "🌀", label: "cyclone" },
    { value: "➿", label: "loop" },
    { value: "🌐", label: "globe with meridians" },
    { value: "Ⓜ️", label: "m" },
    { value: "🏧", label: "atm" },
    { value: "🈂️", label: "sa" },
    { value: "🛂", label: "passport control" },
    { value: "🛃", label: "customs" },
    { value: "🛄", label: "baggage claim" },
    { value: "🛅", label: "left luggage" },
    { value: "♿", label: "wheelchair" },
    { value: "🚭", label: "no smoking" },
    { value: "🚾", label: "wc" },
    { value: "🅿️", label: "parking" },
    { value: "🚰", label: "potable water" },
    { value: "🚹", label: "mens" },
    { value: "🚺", label: "womens" },
    { value: "🚼", label: "baby symbol" },
    { value: "🚻", label: "restroom" },
    { value: "🚮", label: "put litter in its place" },
    { value: "🎦", label: "cinema" },
    { value: "📶", label: "signal strength" },
    { value: "🈁", label: "koko" },
    { value: "🆖", label: "ng" },
    { value: "🆗", label: "ok" },
    { value: "🆙", label: "up" },
    { value: "🆒", label: "cool" },
    { value: "🆕", label: "new" },
    { value: "🆓", label: "free" },
    { value: "0️⃣", label: "zero" },
    { value: "1️⃣", label: "one" },
    { value: "2️⃣", label: "two" },
    { value: "3️⃣", label: "three" },
    { value: "4️⃣", label: "four" },
    { value: "5️⃣", label: "five" },
    { value: "6️⃣", label: "six" },
    { value: "7️⃣", label: "seven" },
    { value: "8️⃣", label: "eight" },
    { value: "9️⃣", label: "nine" },
    { value: "🔟", label: "keycap ten" },
    { value: "*⃣", label: "asterisk" },
    { value: "⏏️", label: "eject button" },
    { value: "▶️", label: "arrow forward" },
    { value: "⏸", label: "pause button" },
    { value: "⏭", label: "next track button" },
    { value: "⏹", label: "stop button" },
    { value: "⏺", label: "record button" },
    { value: "⏯", label: "play or pause button" },
    { value: "⏮", label: "previous track button" },
    { label: "fast forward", value: "⏩" },
    { label: "rewind", value: "⏪" },
    { label: "twisted rightwards arrows", value: "🔀" },
    { label: "repeat button", value: "🔁" },
    { label: "repeat single button", value: "🔂" },
    { label: "arrow up", value: "⬆️" },
    { label: "arrow down", value: "⬇️" },
    { label: "arrow left", value: "⬅️" },
    { label: "arrow right", value: "➡️" },
    { label: "arrow up small", value: "🔼" },
    { label: "arrow down small", value: "🔽" },
  ],
  animals_nature: [
    { label: "dog", value: "🐶" },
    { label: "cat", value: "🐱" },
    { label: "mouse", value: "🐭" },
    { label: "hamster", value: "🐹" },
    { label: "rabbit", value: "🐰" },
    { label: "fox face", value: "🦊" },
    { label: "bear", value: "🐻" },
    { label: "panda face", value: "🐼" },
    { label: "koala", value: "🐨" },
    { label: "tiger", value: "🐯" },
    { label: "lion", value: "🦁" },
    { label: "cow", value: "🐮" },
    { label: "pig", value: "🐷" },
    { label: "pig nose", value: "🐽" },
    { label: "frog", value: "🐸" },
    { label: "squid", value: "🦑" },
    { label: "octopus", value: "🐙" },
    { label: "shrimp", value: "🦐" },
    { label: "monkey face", value: "🐵" },
    { label: "gorilla", value: "🦍" },
    { label: "see no evil", value: "🙈" },
    { label: "hear no evil", value: "🙉" },
    { label: "speak no evil", value: "🙊" },
    { label: "monkey", value: "🐒" },
    { label: "chicken", value: "🐔" },
    { label: "penguin", value: "🐧" },
    { label: "bird", value: "🐦" },
    { label: "baby chick", value: "🐤" },
    { label: "hatching chick", value: "🐣" },
    { label: "hatched chick", value: "🐥" },
    { label: "duck", value: "🦆" },
    { label: "eagle", value: "🦅" },
    { label: "owl", value: "🦉" },
    { label: "bat", value: "🦇" },
    { label: "wolf", value: "🐺" },
    { label: "boar", value: "🐗" },
    { label: "horse", value: "🐴" },
    { label: "unicorn", value: "🦄" },
    { label: "honeybee", value: "🐝" },
    { label: "bug", value: "🐛" },
    { label: "butterfly", value: "🦋" },
    { label: "snail", value: "🐌" },
    { label: "beetle", value: "🐞" },
    { label: "ant", value: "🐜" },
    { label: "grasshopper", value: "🦗" },
    { label: "spider", value: "🕷" },
    { label: "scorpion", value: "🦂" },
    { label: "crab", value: "🦀" },
    { label: "snake", value: "🐍" },
    { label: "lizard", value: "🦎" },
    { label: "t rex", value: "🦖" },
    { label: "sauropod", value: "🦕" },
    { label: "turtle", value: "🐢" },
    { label: "tropical fish", value: "🐠" },
    { label: "fish", value: "🐟" },
    { label: "blowfish", value: "🐡" },
    { label: "dolphin", value: "🐬" },
    { label: "shark", value: "🦈" },
    { label: "whale", value: "🐳" },
    { label: "whale2", value: "🐋" },
    { label: "crocodile", value: "🐊" },
    { label: "leopard", value: "🐆" },
    { label: "zebra", value: "🦓" },
    { label: "tiger2", value: "🐅" },
    { label: "water buffalo", value: "🐃" },
    { label: "ox", value: "🐂" },
    { label: "cow2", value: "🐄" },
    { label: "deer", value: "🦌" },
    { label: "dromedary camel", value: "🐪" },
    { label: "camel", value: "🐫" },
    { label: "giraffe", value: "🦒" },
    { label: "elephant", value: "🐘" },
    { label: "rhinoceros", value: "🦏" },
    { label: "goat", value: "🐐" },
    { label: "ram", value: "🐏" },
    { label: "sheep", value: "🐑" },
    { label: "racehorse", value: "🐎" },
    { label: "pig2", value: "🐖" },
    { label: "rat", value: "🐀" },
    { label: "mouse2", value: "🐁" },
    { label: "rooster", value: "🐓" },
    { label: "turkey", value: "🦃" },
    { label: "dove", value: "🕊" },
    { label: "dog2", value: "🐕" },
    { label: "poodle", value: "🐩" },
    { label: "cat2", value: "🐈" },
    { label: "rabbit2", value: "🐇" },
    { label: "chipmunk", value: "🐿" },
    { label: "hedgehog", value: "🦔" },
    { label: "raccoon", value: "🦝" },
    { label: "llama", value: "🦙" },
    { label: "hippopotamus", value: "🦛" },
    { label: "kangaroo", value: "🦘" },
    { label: "badger", value: "🦡" },
    { label: "swan", value: "🦢" },
    { label: "peacock", value: "🦚" },
    { label: "parrot", value: "🦜" },
    { label: "lobster", value: "🦞" },
    { label: "mosquito", value: "🦟" },
    { label: "paw prints", value: "🐾" },
    { label: "dragon", value: "🐉" },
    { label: "dragon face", value: "🐲" },
    { label: "cactus", value: "🌵" },
    { label: "christmas tree", value: "🎄" },
    { label: "evergreen tree", value: "🌲" },
    { label: "deciduous tree", value: "🌳" },
    { label: "palm tree", value: "🌴" },
    { label: "seedling", value: "🌱" },
    { label: "herb", value: "🌿" },
    { label: "shamrock", value: "☘" },
    { label: "four leaf clover", value: "🍀" },
    { label: "bamboo", value: "🎍" },
    { label: "tanabata tree", value: "🎋" },
    { label: "leaves", value: "🍃" },
    { label: "fallen leaf", value: "🍂" },
    { label: "maple leaf", value: "🍁" },
    { label: "ear of rice", value: "🌾" },
    { label: "hibiscus", value: "🌺" },
    { label: "sunflower", value: "🌻" },
    { label: "rose", value: "🌹" },
    { label: "wilted flower", value: "🥀" },
    { label: "tulip", value: "🌷" },
    { label: "blossom", value: "🌼" },
    { label: "cherry blossom", value: "🌸" },
    { label: "bouquet", value: "💐" },
    { label: "mushroom", value: "🍄" },
    { label: "chestnut", value: "🌰" },
    { label: "jack o lantern", value: "🎃" },
    { label: "shell", value: "🐚" },
    { label: "spider web", value: "🕸" },
    { label: "earth americas", value: "🌎" },
    { label: "earth africa", value: "🌍" },
    { label: "earth asia", value: "🌏" },
    { label: "full moon", value: "🌕" },
    { label: "waning gibbous moon", value: "🌖" },
    { label: "last quarter moon", value: "🌗" },
    { label: "waning crescent moon", value: "🌘" },
    { label: "new moon", value: "🌑" },
    { label: "waxing crescent moon", value: "🌒" },
    { label: "first quarter moon", value: "🌓" },
    { label: "waxing gibbous moon", value: "🌔" },
    { label: "new moon with face", value: "🌚" },
    { label: "full moon with face", value: "🌝" },
    { label: "first quarter moon with face", value: "🌛" },
    { label: "last quarter moon with face", value: "🌜" },
    { label: "sun with face", value: "🌞" },
    { label: "crescent moon", value: "🌙" },
    { label: "star", value: "⭐" },
    { label: "star2", value: "🌟" },
    { label: "dizzy", value: "💫" },
    { label: "sparkles", value: "✨" },
    { label: "comet", value: "☄" },
    { label: "sunny", value: "☀️" },
    { label: "sun behind small cloud", value: "🌤" },
    { label: "partly sunny", value: "⛅" },
    { label: "sun behind large cloud", value: "🌥" },
    { label: "sun behind rain cloud", value: "🌦" },
    { label: "cloud", value: "☁️" },
    { label: "cloud with rain", value: "🌧" },
    { label: "cloud with lightning and rain", value: "⛈" },
    { label: "cloud with lightning", value: "🌩" },
    { label: "zap", value: "⚡" },
    { label: "fire", value: "🔥" },
    { label: "boom", value: "💥" },
    { label: "snowflake", value: "❄️" },
    { label: "cloud with snow", value: "🌨" },
    { label: "snowman", value: "⛄" },
    { label: "snowman with snow", value: "☃" },
    { label: "wind face", value: "🌬" },
    { label: "dash", value: "💨" },
    { label: "tornado", value: "🌪" },
    { label: "fog", value: "🌫" },
    { label: "open umbrella", value: "☂" },
    { label: "umbrella", value: "☔" },
    { label: "droplet", value: "💧" },
    { label: "sweat drops", value: "💦" },
    { label: "ocean", value: "🌊" },
  ],
  food_drink: [
    { label: "green apple", value: "🍏" },
    { label: "apple", value: "🍎" },
    { label: "pear", value: "🍐" },
    { label: "tangerine", value: "🍊" },
    { label: "lemon", value: "🍋" },
    { label: "banana", value: "🍌" },
    { label: "watermelon", value: "🍉" },
    { label: "grapes", value: "🍇" },
    { label: "strawberry", value: "🍓" },
    { label: "melon", value: "🍈" },
    { label: "cherries", value: "🍒" },
    { label: "peach", value: "🍑" },
    { label: "pineapple", value: "🍍" },
    { label: "coconut", value: "🥥" },
    { label: "kiwi fruit", value: "🥝" },
    { label: "mango", value: "🥭" },
    { label: "avocado", value: "🥑" },
    { label: "broccoli", value: "🥦" },
    { label: "tomato", value: "🍅" },
    { label: "eggplant", value: "🍆" },
    { label: "cucumber", value: "🥒" },
    { label: "carrot", value: "🥕" },
    { label: "hot pepper", value: "🌶" },
    { label: "potato", value: "🥔" },
    { label: "corn", value: "🌽" },
    { label: "leafy greens", value: "🥬" },
    { label: "sweet potato", value: "🍠" },
    { label: "peanuts", value: "🥜" },
    { label: "honey pot", value: "🍯" },
    { label: "croissant", value: "🥐" },
    { label: "bread", value: "🍞" },
    { label: "baguette bread", value: "🥖" },
    { label: "bagel", value: "🥯" },
    { label: "pretzel", value: "🥨" },
    { label: "cheese", value: "🧀" },
    { label: "egg", value: "🥚" },
    { label: "bacon", value: "🥓" },
    { label: "steak", value: "🥩" },
    { label: "pancakes", value: "🥞" },
    { label: "poultry leg", value: "🍗" },
    { label: "meat on bone", value: "🍖" },
    { label: "bone", value: "🦴" },
    { label: "fried shrimp", value: "🍤" },
    { label: "fried egg", value: "🍳" },
    { label: "hamburger", value: "🍔" },
    { label: "fries", value: "🍟" },
    { label: "stuffed flatbread", value: "🥙" },
    { label: "hotdog", value: "🌭" },
    { label: "pizza", value: "🍕" },
    { label: "sandwich", value: "🥪" },
    { label: "canned food", value: "🥫" },
    { label: "spaghetti", value: "🍝" },
    { label: "taco", value: "🌮" },
    { label: "burrito", value: "🌯" },
    { label: "green salad", value: "🥗" },
    { label: "shallow pan of food", value: "🥘" },
    { label: "ramen", value: "🍜" },
    { label: "stew", value: "🍲" },
    { label: "fish cake", value: "🍥" },
    { label: "fortune cookie", value: "🥠" },
    { label: "sushi", value: "🍣" },
    { label: "bento", value: "🍱" },
    { label: "curry", value: "🍛" },
    { label: "rice ball", value: "🍙" },
    { label: "rice", value: "🍚" },
    { label: "rice cracker", value: "🍘" },
    { label: "oden", value: "🍢" },
    { label: "dango", value: "🍡" },
    { label: "shaved ice", value: "🍧" },
    { label: "ice cream", value: "🍨" },
    { label: "icecream", value: "🍦" },
    { label: "pie", value: "🥧" },
    { label: "cake", value: "🍰" },
    { label: "cupcake", value: "🧁" },
    { label: "moon cake", value: "🥮" },
    { label: "birthday", value: "🎂" },
    { label: "custard", value: "🍮" },
    { label: "candy", value: "🍬" },
    { label: "lollipop", value: "🍭" },
    { label: "chocolate bar", value: "🍫" },
    { label: "popcorn", value: "🍿" },
    { label: "dumpling", value: "🥟" },
    { label: "doughnut", value: "🍩" },
    { label: "cookie", value: "🍪" },
    { label: "milk glass", value: "🥛" },
    { label: "beer", value: "🍺" },
    { label: "beers", value: "🍻" },
    { label: "clinking glasses", value: "🥂" },
    { label: "wine glass", value: "🍷" },
    { label: "tumbler glass", value: "🥃" },
    { label: "cocktail", value: "🍸" },
    { label: "tropical drink", value: "🍹" },
    { label: "champagne", value: "🍾" },
    { label: "sake", value: "🍶" },
    { label: "tea", value: "🍵" },
    { label: "cup with straw", value: "🥤" },
    { label: "coffee", value: "☕" },
    { label: "baby bottle", value: "🍼" },
    { label: "salt", value: "🧂" },
    { label: "spoon", value: "🥄" },
    { label: "fork and knife", value: "🍴" },
    { label: "plate with cutlery", value: "🍽" },
    { label: "bowl with spoon", value: "🥣" },
    { label: "takeout box", value: "🥡" },
    { label: "chopsticks", value: "🥢" },
  ],
  activities: [
    { label: "soccer", value: "⚽" },
    { label: "basketball", value: "🏀" },
    { label: "football", value: "🏈" },
    { label: "baseball", value: "⚾" },
    { label: "softball", value: "🥎" },
    { label: "tennis", value: "🎾" },
    { label: "volleyball", value: "🏐" },
    { label: "rugby football", value: "🏉" },
    { label: "flying disc", value: "🥏" },
    { label: "8ball", value: "🎱" },
    { label: "golf", value: "⛳" },
    { label: "golfing woman", value: "🏌️‍♀️" },
    { label: "golfing man", value: "🏌" },
    { label: "ping pong", value: "🏓" },
    { label: "badminton", value: "🏸" },
    { label: "goal net", value: "🥅" },
    { label: "ice hockey", value: "🏒" },
    { label: "field hockey", value: "🏑" },
    { label: "lacrosse", value: "🥍" },
    { label: "cricket", value: "🏏" },
    { label: "ski", value: "🎿" },
    { label: "skier", value: "⛷" },
    { label: "snowboarder", value: "🏂" },
    { label: "person fencing", value: "🤺" },
    { label: "women wrestling", value: "🤼‍♀️" },
    { label: "men wrestling", value: "🤼‍♂️" },
    { label: "woman cartwheeling", value: "🤸‍♀️" },
    { label: "man cartwheeling", value: "🤸‍♂️" },
    { label: "woman playing handball", value: "🤾‍♀️" },
    { label: "man playing handball", value: "🤾‍♂️" },
    { label: "ice skate", value: "⛸" },
    { label: "curling stone", value: "🥌" },
    { label: "skateboard", value: "🛹" },
    { label: "sled", value: "🛷" },
    { label: "bow and arrow", value: "🏹" },
    { label: "fishing pole and fish", value: "🎣" },
    { label: "boxing glove", value: "🥊" },
    { label: "martial arts uniform", value: "🥋" },
    { label: "rowing woman", value: "🚣‍♀️" },
    { label: "rowing man", value: "🚣" },
    { label: "climbing woman", value: "🧗‍♀️" },
    { label: "climbing man", value: "🧗‍♂️" },
    { label: "swimming woman", value: "🏊‍♀️" },
    { label: "swimming man", value: "🏊" },
    { label: "woman playing water polo", value: "🤽‍♀️" },
    { label: "man playing water polo", value: "🤽‍♂️" },
    { label: "woman in lotus position", value: "🧘‍♀️" },
    { label: "man in lotus position", value: "🧘‍♂️" },
    { label: "surfing woman", value: "🏄‍♀️" },
    { label: "surfing man", value: "🏄" },
    { label: "bath", value: "🛀" },
    { label: "basketball woman", value: "⛹️‍♀️" },
    { label: "basketball man", value: "⛹" },
    { label: "weight lifting woman", value: "🏋️‍♀️" },
    { label: "weight lifting man", value: "🏋" },
    { label: "biking woman", value: "🚴‍♀️" },
    { label: "biking man", value: "🚴" },
    { label: "mountain biking woman", value: "🚵‍♀️" },
    { label: "mountain biking man", value: "🚵" },
    { label: "horse racing", value: "🏇" },
    { label: "business suit levitating", value: "🕴" },
    { label: "trophy", value: "🏆" },
    { label: "running shirt with sash", value: "🎽" },
    { label: "medal sports", value: "🏅" },
    { label: "medal military", value: "🎖" },
    { label: "1st place medal", value: "🥇" },
    { label: "2nd place medal", value: "🥈" },
    { label: "3rd place medal", value: "🥉" },
    { label: "reminder ribbon", value: "🎗" },
    { label: "rosette", value: "🏵" },
    { label: "ticket", value: "🎫" },
    { label: "tickets", value: "🎟" },
    { label: "performing arts", value: "🎭" },
    { label: "art", value: "🎨" },
    { label: "circus tent", value: "🎪" },
    { label: "woman juggling", value: "🤹‍♀️" },
    { label: "man juggling", value: "🤹‍♂️" },
    { label: "microphone", value: "🎤" },
    { label: "headphones", value: "🎧" },
    { label: "musical score", value: "🎼" },
    { label: "musical keyboard", value: "🎹" },
    { label: "drum", value: "🥁" },
    { label: "saxophone", value: "🎷" },
    { label: "trumpet", value: "🎺" },
    { label: "guitar", value: "🎸" },
    { label: "violin", value: "🎻" },
    { label: "clapper", value: "🎬" },
    { label: "video game", value: "🎮" },
    { label: "space invader", value: "👾" },
    { label: "dart", value: "🎯" },
    { label: "game die", value: "🎲" },
    { label: "chess pawn", value: "♟" },
    { label: "slot machine", value: "🎰" },
    { label: "jigsaw", value: "🧩" },
    { label: "bowling", value: "🎳" },
  ],
  travel_places: [
    { label: "red car", value: "🚗" },
    { label: "taxi", value: "🚕" },
    { label: "blue car", value: "🚙" },
    { label: "bus", value: "🚌" },
    { label: "trolleybus", value: "🚎" },
    { label: "racing car", value: "🏎" },
    { label: "police car", value: "🚓" },
    { label: "ambulance", value: "🚑" },
    { label: "fire engine", value: "🚒" },
    { label: "minibus", value: "🚐" },
    { label: "truck", value: "🚚" },
    { label: "articulated lorry", value: "🚛" },
    { label: "tractor", value: "🚜" },
    { label: "kick scooter", value: "🛴" },
    { label: "motorcycle", value: "🏍" },
    { label: "bike", value: "🚲" },
    { label: "motor scooter", value: "🛵" },
    { label: "rotating light", value: "🚨" },
    { label: "oncoming police car", value: "🚔" },
    { label: "oncoming bus", value: "🚍" },
    { label: "oncoming automobile", value: "🚘" },
    { label: "oncoming taxi", value: "🚖" },
    { label: "aerial tramway", value: "🚡" },
    { label: "mountain cableway", value: "🚠" },
    { label: "suspension railway", value: "🚟" },
    { label: "railway car", value: "🚃" },
    { label: "train", value: "🚋" },
    { label: "monorail", value: "🚝" },
    { label: "bullettrain side", value: "🚄" },
    { label: "bullettrain front", value: "🚅" },
    { label: "light rail", value: "🚈" },
    { label: "mountain railway", value: "🚞" },
    { label: "steam locomotive", value: "🚂" },
    { label: "train2", value: "🚆" },
    { label: "metro", value: "🚇" },
    { label: "tram", value: "🚊" },
    { label: "station", value: "🚉" },
    { label: "flying saucer", value: "🛸" },
    { label: "helicopter", value: "🚁" },
    { label: "small airplane", value: "🛩" },
    { label: "airplane", value: "✈️" },
    { label: "flight departure", value: "🛫" },
    { label: "flight arrival", value: "🛬" },
    { label: "sailboat", value: "⛵" },
    { label: "motor boat", value: "🛥" },
    { label: "speedboat", value: "🚤" },
    { label: "ferry", value: "⛴" },
    { label: "passenger ship", value: "🛳" },
    { label: "rocket", value: "🚀" },
    { label: "artificial satellite", value: "🛰" },
    { label: "seat", value: "💺" },
    { label: "canoe", value: "🛶" },
    { label: "anchor", value: "⚓" },
    { label: "construction", value: "🚧" },
    { label: "fuelpump", value: "⛽" },
    { label: "busstop", value: "🚏" },
    { label: "vertical traffic light", value: "🚦" },
    { label: "traffic light", value: "🚥" },
    { label: "checkered flag", value: "🏁" },
    { label: "ship", value: "🚢" },
    { label: "ferris wheel", value: "🎡" },
    { label: "roller coaster", value: "🎢" },
    { label: "carousel horse", value: "🎠" },
    { label: "building construction", value: "🏗" },
    { label: "foggy", value: "🌁" },
    { label: "tokyo tower", value: "🗼" },
    { label: "factory", value: "🏭" },
    { label: "fountain", value: "⛲" },
    { label: "rice scene", value: "🎑" },
    { label: "mountain", value: "⛰" },
    { label: "mountain snow", value: "🏔" },
    { label: "mount fuji", value: "🗻" },
    { label: "volcano", value: "🌋" },
    { label: "japan", value: "🗾" },
    { label: "camping", value: "🏕" },
    { label: "tent", value: "⛺" },
    { label: "national park", value: "🏞" },
    { label: "motorway", value: "🛣" },
    { label: "railway track", value: "🛤" },
    { label: "sunrise", value: "🌅" },
    { label: "sunrise over mountains", value: "🌄" },
    { label: "desert", value: "🏜" },
    { label: "beach umbrella", value: "🏖" },
    { label: "desert island", value: "🏝" },
    { label: "city sunrise", value: "🌇" },
    { label: "city sunset", value: "🌆" },
    { label: "cityscape", value: "🏙" },
    { label: "night with stars", value: "🌃" },
    { label: "bridge at night", value: "🌉" },
    { label: "milky way", value: "🌌" },
    { label: "stars", value: "🌠" },
    { label: "sparkler", value: "🎇" },
    { label: "fireworks", value: "🎆" },
    { label: "rainbow", value: "🌈" },
    { label: "houses", value: "🏘" },
    { label: "european castle", value: "🏰" },
    { label: "japanese castle", value: "🏯" },
    { label: "stadium", value: "🏟" },
    { label: "statue of liberty", value: "🗽" },
    { label: "house", value: "🏠" },
    { label: "house with garden", value: "🏡" },
    { label: "derelict house", value: "🏚" },
    { label: "office", value: "🏢" },
    { label: "department store", value: "🏬" },
    { label: "post office", value: "🏣" },
    { label: "european post office", value: "🏤" },
    { label: "hospital", value: "🏥" },
    { label: "bank", value: "🏦" },
    { label: "hotel", value: "🏨" },
    { label: "convenience store", value: "🏪" },
    { label: "school", value: "🏫" },
    { label: "love hotel", value: "🏩" },
    { label: "wedding", value: "💒" },
    { label: "classical building", value: "🏛" },
    { label: "church", value: "⛪" },
    { label: "mosque", value: "🕌" },
    { label: "synagogue", value: "🕍" },
    { label: "kaaba", value: "🕋" },
    { label: "shinto shrine", value: "⛩" },
  ],
  objects: [
    { label: "watch", value: "⌚" },
    { label: "iphone", value: "📱" },
    { label: "calling", value: "📲" },
    { label: "computer", value: "💻" },
    { label: "keyboard", value: "⌨" },
    { label: "desktop computer", value: "🖥" },
    { label: "printer", value: "🖨" },
    { label: "computer mouse", value: "🖱" },
    { label: "trackball", value: "🖲" },
    { label: "joystick", value: "🕹" },
    { label: "clamp", value: "🗜" },
    { label: "minidisc", value: "💽" },
    { label: "floppy disk", value: "💾" },
    { label: "cd", value: "💿" },
    { label: "dvd", value: "📀" },
    { label: "vhs", value: "📼" },
    { label: "camera", value: "📷" },
    { label: "camera flash", value: "📸" },
    { label: "video camera", value: "📹" },
    { label: "movie camera", value: "🎥" },
    { label: "film projector", value: "📽" },
    { label: "film strip", value: "🎞" },
    { label: "telephone receiver", value: "📞" },
    { label: "phone", value: "☎️" },
    { label: "pager", value: "📟" },
    { label: "fax", value: "📠" },
    { label: "tv", value: "📺" },
    { label: "radio", value: "📻" },
    { label: "studio microphone", value: "🎙" },
    { label: "level slider", value: "🎚" },
    { label: "control knobs", value: "🎛" },
    { label: "compass", value: "🧭" },
    { label: "stopwatch", value: "⏱" },
    { label: "timer clock", value: "⏲" },
    { label: "alarm clock", value: "⏰" },
    { label: "mantelpiece clock", value: "🕰" },
    { label: "hourglass flowing sand", value: "⏳" },
    { label: "hourglass", value: "⌛" },
    { label: "satellite", value: "📡" },
    { label: "battery", value: "🔋" },
    { label: "electric plug", value: "🔌" },
    { label: "bulb", value: "💡" },
    { label: "flashlight", value: "🔦" },
    { label: "candle", value: "🕯" },
    { label: "fire extinguisher", value: "🧯" },
    { label: "wastebasket", value: "🗑" },
    { label: "oil drum", value: "🛢" },
    { label: "money with wings", value: "💸" },
    { label: "dollar", value: "💵" },
    { label: "yen", value: "💴" },
    { label: "euro", value: "💶" },
    { label: "pound", value: "💷" },
    { label: "moneybag", value: "💰" },
    { label: "credit card", value: "💳" },
    { label: "gem", value: "💎" },
    { label: "balance scale", value: "⚖" },
    { label: "toolbox", value: "🧰" },
    { label: "wrench", value: "🔧" },
    { label: "hammer", value: "🔨" },
    { label: "hammer and pick", value: "⚒" },
    { label: "hammer and wrench", value: "🛠" },
    { label: "pick", value: "⛏" },
    { label: "nut and bolt", value: "🔩" },
    { label: "gear", value: "⚙" },
    { label: "brick", value: "🧱" },
    { label: "chains", value: "⛓" },
    { label: "magnet", value: "🧲" },
    { label: "gun", value: "🔫" },
    { label: "bomb", value: "💣" },
    { label: "firecracker", value: "🧨" },
    { label: "hocho", value: "🔪" },
    { label: "dagger", value: "🗡" },
    { label: "crossed swords", value: "⚔" },
    { label: "shield", value: "🛡" },
    { label: "smoking", value: "🚬" },
    { label: "skull and crossbones", value: "☠" },
    { label: "coffin", value: "⚰" },
    { label: "funeral urn", value: "⚱" },
    { label: "amphora", value: "🏺" },
    { label: "crystal ball", value: "🔮" },
    { label: "prayer beads", value: "📿" },
    { label: "nazar amulet", value: "🧿" },
    { label: "barber", value: "💈" },
    { label: "alembic", value: "⚗" },
    { label: "telescope", value: "🔭" },
    { label: "microscope", value: "🔬" },
    { label: "hole", value: "🕳" },
    { label: "pill", value: "💊" },
    { label: "syringe", value: "💉" },
    { label: "dna", value: "🧬" },
    { label: "microbe", value: "🦠" },
    { label: "petri dish", value: "🧫" },
    { label: "test tube", value: "🧪" },
    { label: "thermometer", value: "🌡" },
    { label: "broom", value: "🧹" },
    { label: "basket", value: "🧺" },
    { label: "toilet paper", value: "🧻" },
    { label: "label", value: "🏷" },
    { label: "bookmark", value: "🔖" },
    { label: "toilet", value: "🚽" },
    { label: "shower", value: "🚿" },
    { label: "bathtub", value: "🛁" },
    { label: "soap", value: "🧼" },
    { label: "sponge", value: "🧽" },
    { label: "lotion bottle", value: "🧴" },
    { label: "key", value: "🔑" },
    { label: "old key", value: "🗝" },
    { label: "couch and lamp", value: "🛋" },
    { label: "sleeping bed", value: "🛌" },
    { label: "bed", value: "🛏" },
    { label: "door", value: "🚪" },
    { label: "bellhop bell", value: "🛎" },
    { label: "teddy bear", value: "🧸" },
    { label: "framed picture", value: "🖼" },
    { label: "world map", value: "🗺" },
    { label: "parasol on ground", value: "⛱" },
    { label: "moyai", value: "🗿" },
    { label: "shopping", value: "🛍" },
    { label: "shopping cart", value: "🛒" },
    { label: "balloon", value: "🎈" },
    { label: "flags", value: "🎏" },
    { label: "ribbon", value: "🎀" },
    { label: "gift", value: "🎁" },
    { label: "confetti ball", value: "🎊" },
    { label: "tada", value: "🎉" },
    { label: "dolls", value: "🎎" },
    { label: "wind chime", value: "🎐" },
    { label: "crossed flags", value: "🎌" },
    { label: "izakaya lantern", value: "🏮" },
    { label: "red envelope", value: "🧧" },
    { label: "email", value: "✉️" },
    { label: "envelope with arrow", value: "📩" },
    { label: "incoming envelope", value: "📨" },
    { label: "e mail", value: "📧" },
    { label: "love letter", value: "💌" },
    { label: "postbox", value: "📮" },
    { label: "mailbox closed", value: "📪" },
    { label: "mailbox", value: "📫" },
    { label: "mailbox with mail", value: "📬" },
    { label: "mailbox with no mail", value: "📭" },
    { label: "package", value: "📦" },
    { label: "postal horn", value: "📯" },
    { label: "inbox tray", value: "📥" },
    { label: "outbox tray", value: "📤" },
    { label: "scroll", value: "📜" },
    { label: "page with curl", value: "📃" },
    { label: "bookmark tabs", value: "📑" },
    { label: "receipt", value: "🧾" },
    { label: "bar chart", value: "📊" },
    { label: "chart with upwards trend", value: "📈" },
    { label: "chart with downwards trend", value: "📉" },
    { label: "page facing up", value: "📄" },
    { label: "date", value: "📅" },
    { label: "calendar", value: "📆" },
    { label: "spiral calendar", value: "🗓" },
    { label: "card index", value: "📇" },
    { label: "card file box", value: "🗃" },
    { label: "ballot box", value: "🗳" },
    { label: "file cabinet", value: "🗄" },
    { label: "clipboard", value: "📋" },
    { label: "spiral notepad", value: "🗒" },
    { label: "file folder", value: "📁" },
    { label: "open file folder", value: "📂" },
    { label: "card index dividers", value: "🗂" },
    { label: "newspaper roll", value: "🗞" },
    { label: "newspaper", value: "📰" },
    { label: "notebook", value: "📓" },
    { label: "closed book", value: "📕" },
    { label: "green book", value: "📗" },
    { label: "blue book", value: "📘" },
    { label: "orange book", value: "📙" },
    { label: "notebook with decorative cover", value: "📔" },
    { label: "ledger", value: "📒" },
    { label: "books", value: "📚" },
    { label: "open book", value: "📖" },
    { label: "safety pin", value: "🧷" },
    { label: "link", value: "🔗" },
    { label: "paperclip", value: "📎" },
    { label: "paperclips", value: "🖇" },
    { label: "scissors", value: "✂️" },
    { label: "triangular ruler", value: "📐" },
    { label: "straight ruler", value: "📏" },
    { label: "abacus", value: "🧮" },
    { label: "pushpin", value: "📌" },
    { label: "round pushpin", value: "📍" },
    { label: "triangular flag on post", value: "🚩" },
    { label: "white flag", value: "🏳" },
    { label: "black flag", value: "🏴" },
    { label: "closed lock with key", value: "🔐" },
    { label: "lock", value: "🔒" },
    { label: "unlock", value: "🔓" },
    { label: "lock with ink pen", value: "🔏" },
    { label: "pen", value: "🖊" },
    { label: "fountain pen", value: "🖋" },
    { label: "black nib", value: "✒️" },
    { label: "memo", value: "📝" },
    { label: "pencil2", value: "✏️" },
    { label: "crayon", value: "🖍" },
    { label: "paintbrush", value: "🖌" },
    { label: "mag", value: "🔍" },
    { label: "mag right", value: "🔎" },
  ],
  flags: [
    { label: "afghanistan", value: "🇦🇫" },
    { label: "aland islands", value: "🇦🇽" },
    { label: "albania", value: "🇦🇱" },
    { label: "algeria", value: "🇩🇿" },
    { label: "american samoa", value: "🇦🇸" },
    { label: "andorra", value: "🇦🇩" },
    { label: "angola", value: "🇦🇴" },
    { label: "anguilla", value: "🇦🇮" },
    { label: "antarctica", value: "🇦🇶" },
    { label: "antigua barbuda", value: "🇦🇬" },
    { label: "argentina", value: "🇦🇷" },
    { label: "armenia", value: "🇦🇲" },
    { label: "aruba", value: "🇦🇼" },
    { label: "australia", value: "🇦🇺" },
    { label: "austria", value: "🇦🇹" },
    { label: "azerbaijan", value: "🇦🇿" },
    { label: "bahamas", value: "🇧🇸" },
    { label: "bahrain", value: "🇧🇭" },
    { label: "bangladesh", value: "🇧🇩" },
    { label: "barbados", value: "🇧🇧" },
    { label: "belarus", value: "🇧🇾" },
    { label: "belgium", value: "🇧🇪" },
    { label: "belize", value: "🇧🇿" },
    { label: "benin", value: "🇧🇯" },
    { label: "bermuda", value: "🇧🇲" },
    { label: "bhutan", value: "🇧🇹" },
    { label: "bolivia", value: "🇧🇴" },
    { label: "caribbean netherlands", value: "🇧🇶" },
    { label: "bosnia herzegovina", value: "🇧🇦" },
    { label: "botswana", value: "🇧🇼" },
    { label: "brazil", value: "🇧🇷" },
    { label: "british indian ocean territory", value: "🇮🇴" },
    { label: "british virgin islands", value: "🇻🇬" },
    { label: "brunei", value: "🇧🇳" },
    { label: "bulgaria", value: "🇧🇬" },
    { label: "burkina faso", value: "🇧🇫" },
    { label: "burundi", value: "🇧🇮" },
    { label: "cape verde", value: "🇨🇻" },
    { label: "cambodia", value: "🇰🇭" },
    { label: "cameroon", value: "🇨🇲" },
    { label: "canada", value: "🇨🇦" },
    { label: "canary islands", value: "🇮🇨" },
    { label: "cayman islands", value: "🇰🇾" },
    { label: "central african republic", value: "🇨🇫" },
    { label: "chad", value: "🇹🇩" },
    { label: "chile", value: "🇨🇱" },
    { label: "cn", value: "🇨🇳" },
    { label: "christmas island", value: "🇨🇽" },
    { label: "cocos islands", value: "🇨🇨" },
    { label: "colombia", value: "🇨🇴" },
    { label: "comoros", value: "🇰🇲" },
    { label: "congo brazzaville", value: "🇨🇬" },
    { label: "congo kinshasa", value: "🇨🇩" },
    { label: "cook islands", value: "🇨🇰" },
    { label: "costa rica", value: "🇨🇷" },
    { label: "croatia", value: "🇭🇷" },
    { label: "cuba", value: "🇨🇺" },
    { label: "curacao", value: "🇨🇼" },
    { label: "cyprus", value: "🇨🇾" },
    { label: "czech republic", value: "🇨🇿" },
    { label: "denmark", value: "🇩🇰" },
    { label: "djibouti", value: "🇩🇯" },
    { label: "dominica", value: "🇩🇲" },
    { label: "dominican republic", value: "🇩🇴" },
    { label: "ecuador", value: "🇪🇨" },
    { label: "egypt", value: "🇪🇬" },
    { label: "el salvador", value: "🇸🇻" },
    { label: "equatorial guinea", value: "🇬🇶" },
    { label: "eritrea", value: "🇪🇷" },
    { label: "estonia", value: "🇪🇪" },
    { label: "ethiopia", value: "🇪🇹" },
    { label: "eu", value: "🇪🇺" },
    { label: "falkland islands", value: "🇫🇰" },
    { label: "faroe islands", value: "🇫🇴" },
    { label: "fiji", value: "🇫🇯" },
    { label: "finland", value: "🇫🇮" },
    { label: "fr", value: "🇫🇷" },
    { label: "french guiana", value: "🇬🇫" },
    { label: "french polynesia", value: "🇵🇫" },
    { label: "french southern territories", value: "🇹🇫" },
    { label: "gabon", value: "🇬🇦" },
    { label: "gambia", value: "🇬🇲" },
    { label: "georgia", value: "🇬🇪" },
    { label: "de", value: "🇩🇪" },
    { label: "ghana", value: "🇬🇭" },
    { label: "gibraltar", value: "🇬🇮" },
    { label: "greece", value: "🇬🇷" },
    { label: "greenland", value: "🇬🇱" },
    { label: "grenada", value: "🇬🇩" },
    { label: "guadeloupe", value: "🇬🇵" },
    { label: "guam", value: "🇬🇺" },
    { label: "guatemala", value: "🇬🇹" },
    { label: "guernsey", value: "🇬🇬" },
    { label: "guinea", value: "🇬🇳" },
    { label: "guinea bissau", value: "🇬🇼" },
    { label: "guyana", value: "🇬🇾" },
    { label: "haiti", value: "🇭🇹" },
    { label: "honduras", value: "🇭🇳" },
    { label: "hong kong", value: "🇭🇰" },
    { label: "hungary", value: "🇭🇺" },
    { label: "iceland", value: "🇮🇸" },
    { label: "india", value: "🇮🇳" },
    { label: "indonesia", value: "🇮🇩" },
    { label: "iran", value: "🇮🇷" },
    { label: "iraq", value: "🇮🇶" },
    { label: "ireland", value: "🇮🇪" },
    { label: "isle of man", value: "🇮🇲" },
    { label: "israel", value: "🇮🇱" },
    { label: "it", value: "🇮🇹" },
    { label: "cote divoire", value: "🇨🇮" },
    { label: "jamaica", value: "🇯🇲" },
    { label: "jp", value: "🇯🇵" },
    { label: "jersey", value: "🇯🇪" },
    { label: "jordan", value: "🇯🇴" },
    { label: "kazakhstan", value: "🇰🇿" },
    { label: "kenya", value: "🇰🇪" },
    { label: "kiribati", value: "🇰🇮" },
    { label: "kosovo", value: "🇽🇰" },
    { label: "kuwait", value: "🇰🇼" },
    { label: "kyrgyzstan", value: "🇰🇬" },
    { label: "laos", value: "🇱🇦" },
    { label: "latvia", value: "🇱🇻" },
    { label: "lebanon", value: "🇱🇧" },
    { label: "lesotho", value: "🇱🇸" },
    { label: "liberia", value: "🇱🇷" },
    { label: "libya", value: "🇱🇾" },
    { label: "liechtenstein", value: "🇱🇮" },
    { label: "lithuania", value: "🇱🇹" },
    { label: "luxembourg", value: "🇱🇺" },
    { label: "macau", value: "🇲🇴" },
    { label: "macedonia", value: "🇲🇰" },
    { label: "madagascar", value: "🇲🇬" },
    { label: "malawi", value: "🇲🇼" },
    { label: "malaysia", value: "🇲🇾" },
    { label: "maldives", value: "🇲🇻" },
    { label: "mali", value: "🇲🇱" },
    { label: "malta", value: "🇲🇹" },
    { label: "marshall islands", value: "🇲🇭" },
    { label: "martinique", value: "🇲🇶" },
    { label: "mauritania", value: "🇲🇷" },
    { label: "mauritius", value: "🇲🇺" },
    { label: "mayotte", value: "🇾🇹" },
    { label: "mexico", value: "🇲🇽" },
    { label: "micronesia", value: "🇫🇲" },
    { label: "moldova", value: "🇲🇩" },
    { label: "monaco", value: "🇲🇨" },
    { label: "mongolia", value: "🇲🇳" },
    { label: "montenegro", value: "🇲🇪" },
    { label: "montserrat", value: "🇲🇸" },
    { label: "morocco", value: "🇲🇦" },
    { label: "mozambique", value: "🇲🇿" },
    { label: "myanmar", value: "🇲🇲" },
    { label: "namibia", value: "🇳🇦" },
    { label: "nauru", value: "🇳🇷" },
    { label: "nepal", value: "🇳🇵" },
    { label: "netherlands", value: "🇳🇱" },
    { label: "new caledonia", value: "🇳🇨" },
    { label: "new zealand", value: "🇳🇿" },
    { label: "nicaragua", value: "🇳🇮" },
    { label: "niger", value: "🇳🇪" },
    { label: "nigeria", value: "🇳🇬" },
    { label: "niue", value: "🇳🇺" },
    { label: "norfolk island", value: "🇳🇫" },
    { label: "northern mariana islands", value: "🇲🇵" },
    { label: "north korea", value: "🇰🇵" },
    { label: "norway", value: "🇳🇴" },
    { label: "oman", value: "🇴🇲" },
    { label: "pakistan", value: "🇵🇰" },
    { label: "palau", value: "🇵🇼" },
    { label: "palestinian territories", value: "🇵🇸" },
    { label: "panama", value: "🇵🇦" },
    { label: "papua new guinea", value: "🇵🇬" },
    { label: "paraguay", value: "🇵🇾" },
    { label: "peru", value: "🇵🇪" },
    { label: "philippines", value: "🇵🇭" },
    { label: "pitcairn islands", value: "🇵🇳" },
    { label: "poland", value: "🇵🇱" },
    { label: "portugal", value: "🇵🇹" },
    { label: "puerto rico", value: "🇵🇷" },
    { label: "qatar", value: "🇶🇦" },
    { label: "reunion", value: "🇷🇪" },
    { label: "romania", value: "🇷🇴" },
    { label: "ru", value: "🇷🇺" },
    { label: "rwanda", value: "🇷🇼" },
    { label: "st barthelemy", value: "🇧🇱" },
    { label: "st helena", value: "🇸🇭" },
    { label: "st kitts nevis", value: "🇰🇳" },
    { label: "st lucia", value: "🇱🇨" },
    { label: "st pierre miquelon", value: "🇵🇲" },
    { label: "st vincent grenadines", value: "🇻🇨" },
    { label: "samoa", value: "🇼🇸" },
    { label: "san marino", value: "🇸🇲" },
    { label: "sao tome principe", value: "🇸🇹" },
    { label: "saudi arabia", value: "🇸🇦" },
    { label: "senegal", value: "🇸🇳" },
    { label: "serbia", value: "🇷🇸" },
    { label: "seychelles", value: "🇸🇨" },
    { label: "sierra leone", value: "🇸🇸" },
    { label: "singapore", value: "🇸🇬" },
    { label: "sint maarten", value: "🇸🇽" },
    { label: "slovakia", value: "🇸🇰" },
    { label: "solomon islands", value: "🇸🇧" },
    { label: "somalia", value: "🇸🇴" },
    { label: "south africa", value: "🇿🇦" },
    { label: "south georgia south sandwich islands", value: "🇬🇸" },
    { label: "kr", value: "🇰🇷" },
    { label: "south sudan", value: "🇸🇸" },
    { label: "es", value: "🇪🇸" },
    { label: "sri lanka", value: "🇱🇰" },
    { label: "sudan", value: "🇸🇩" },
    { label: "suriname", value: "🇸🇷" },
    { label: "swaziland", value: "🇸🇿" },
    { label: "sweden", value: "🇸🇪" },
    { label: "switzerland", value: "🇨🇭" },
    { label: "syria", value: "🇸🇾" },
    { label: "taiwan", value: "🇹🇼" },
    { label: "tajikistan", value: "🇹🇯" },
    { label: "tanzania", value: "🇹🇿" },
    { label: "thailand", value: "🇹🇭" },
    { label: "timor leste", value: "🇹🇱" },
    { label: "togo", value: "🇹🇬" },
    { label: "tokelau", value: "🇹🇰" },
    { label: "tonga", value: "🇹🇴" },
    { label: "trinidad tobago", value: "🇹🇹" },
    { label: "tunisia", value: "🇹🇳" },
    { label: "tr", value: "🇹🇷" },
    { label: "turkmenistan", value: "🇹🇲" },
    { label: "turks caicos islands", value: "🇹🇨" },
    { label: "tuvalu", value: "🇹🇻" },
    { label: "uganda", value: "🇺🇬" },
    { label: "ukraine", value: "🇺🇦" },
    { label: "united arab emirates", value: "🇦🇪" },
    { label: "uk", value: "🇬🇧" },
    { label: "england", value: "🏴" },
    { label: "scotland", value: "🏴" },
    { label: "wales", value: "🏴" },
    { label: "us", value: "🇺🇸" },
    { label: "us virgin islands", value: "🇻🇮" },
    { label: "uruguay", value: "🇺🇾" },
    { label: "uzbekistan", value: "🇺🇿" },
    { label: "vanuatu", value: "🇻🇺" },
    { label: "vatican city", value: "🇻🇦" },
    { label: "venezuela", value: "🇻🇪" },
    { label: "vietnam", value: "🇻🇳" },
    { label: "wallis futuna", value: "🇼🇫" },
    { label: "western sahara", value: "🇪🇭" },
    { label: "yemen", value: "🇾🇪" },
    { label: "zambia", value: "🇿🇲" },
    { label: "zimbabwe", value: "🇿🇼" },
    { label: "united nations", value: "🇺🇳" },
    { label: "pirate flag", value: "🏴‍☠️" },
  ],
};

const selectCategory = (category: EmojisCategories) =>
  (selectedCategory.value = category);

const filteredCharacters = computed(() => {
  const category = selectedCategory.value;
  if (!category) return;
  return characters[category].filter(
    (c: Emoji) =>
      c.label.includes(search.value) || c.value.includes(search.value)
  );
});

const insertCharacter = (character: string) => {
  props.editor.commands.insertContent(character);
  notify("کاراکتر موردنظر اعمال شد!");
};
</script>

<style lang="scss" scoped>
* {
  font-family: var(--tiptap-editor-font);
}
.chars-container {
  display: flex;
  flex-wrap: wrap;
  max-height: 20rem;
  overflow-y: auto;
}

.char-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  font-family: inherit;
  font-size: 1.25rem;
  margin: 0.5rem;
  padding: 0.5rem;
  width: 30px;
  height: 30px;
  line-height: 1;
  border-radius: 5px;
  &:hover {
    background-color: #f1f1f1;
  }
}

.bg-grey-lighten-4 {
  background-color: #f5f5f5;
}

.card-title {
  font-size: 1.125rem;
  font-weight: 600;
  line-height: 1.75rem;
}

.button {
  padding: 1rem;
}
</style>
